# ======================
# Database
# ======================
[db-master]
db-m ansible_host=172.16.6.141 ansible_user=root ansible_password=soldesk5.

[db-slave]
db-s ansible_host=172.16.6.142 ansible_user=root ansible_password=soldesk5.

[db-extra]
db-o ansible_host=172.16.6.143 ansible_user=root
db-b ansible_host=172.16.6.144 ansible_user=root

[database:children]
db-master
db-slave
db-extra


# ======================
# WEB + WAS
# ======================
[web]
web1 ansible_host=172.16.6.94 ansible_user=root

# ======================
# LB (Load Balancer)
# ======================
[lb_servers]
lb1 ansible_host=172.16.6.95 ansible_user=root keepalived_state=MASTER keepalived_priority=150
lb2 ansible_host=172.16.6.96 ansible_user=root keepalived_state=BACKUP keepalived_priority=100

[loadbalancer:children]
lb_servers

# ======================
# WAF
# ======================
[waf]
waf ansible_host=172.16.6.99 ansible_user=root

# ======================
# DNS + Prometheus + Grafana
# ======================
[dns]
project-dns ansible_host=172.16.6.91 ansible_user=soldesk ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true

[monitoring]
monitoring-pg ansible_host=172.16.6.91 ansible_user=soldesk ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true

# ======================
# Jenkins (CI/CD)
# ======================
[cicd]
jenkins ansible_host=172.16.6.145 ansible_user=jenkins ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa

# ======================
# Ansible Control Server
# ======================
#[ansible_controller]
#ansible-ctrl ansible_host=172.16.6.98 ansible_user=root

# ======================
# 전체 그룹
# ======================
[all_servers:children]
database
web
waf
loadbalancer
dns
monitoring
cicd

