[db-master]
db-m ansible_host=172.16.6.141 ansible_user=root master_host=172.16.6.141

[db-slave]
db-s ansible_host=172.16.6.142 ansible_user=root master_host=172.16.6.141

[db-extra]
db-os ansible_host=172.16.6.143 ansible_user=root
db-bs ansible_host=172.16.6.144 ansible_user=root

[web]
web1 ansible_host=172.16.6.94

[waf]
waf ansible_host=172.16.6.99 ansible_user=root

[lb_servers]
lb1 ansible_host=172.16.6.95 keepalived_state=MASTER keepalived_priority=150
lb2 ansible_host=172.16.6.96 keepalived_state=MASTER keepalived_priority=100

[cicd]
project-cicd ansible_host=172.16.6.145 ansible_user=jenkins ansible_ssh_private_key_file=~/.ssh/id_rsa

[dns]
project-dns ansible_host=172.16.6.91 ansible_user=soldesk ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true

[monitoring]
project-dns ansible_host=172.16.6.91 ansible_user=soldesk ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true


# 전체 DB를 한 번에 관리하고 싶을 때
[database:children]
db-master
db-slave
db-extra

# 전체 LB 관리
[loadbalancer:children]
lb_servers

# 전체 관리 (필요하면)
[all_servers:children]
database
web
waf
loadbalancer
cicd

